# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=2000)),
                ('Attachment', models.FileField(upload_to='Coursework')),
                ('Score', models.IntegerField(max_length=10)),
                ('Comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Credit', models.FloatField(max_length=10)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Duration', models.DurationField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=2000)),
                ('Start_Time', models.DateTimeField()),
                ('End_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=2000)),
                ('Attachment', models.FileField(upload_to='Resource')),
                ('Category', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Duration_Weeks', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Teacher'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Student'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='Enrolled_Students',
            field=models.ManyToManyField(through='CoPlat.Assignment', to='CoPlat.Student'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='Course_Instructors',
            field=models.ManyToManyField(through='CoPlat.Instruction', to='CoPlat.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='Enrolled_Students',
            field=models.ManyToManyField(through='CoPlat.Enrollment', to='CoPlat.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Coursework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Coursework'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoPlat.Student'),
        ),
    ]
