# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoPlat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='Duration_Weeks',
            field=models.IntegerField(),
        ),
    ]
